# -*- coding: utf-8 -*-
"""TextClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2SiKmORQqaKNwK2BJh1e6HhiMEHki3h
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow_hub as hub

df = pd.read_csv('/content/wine-reviews.csv', usecols = ['country', 'description', 'points', 'price', 'variety', 'winery'])

df.head()

df = df.dropna(subset=["description", "points"])

df.head()

plt.hist(df.points, bins=20)
plt.title("Points histogram")
plt.ylabel("N")
plt.xlabel("Points")
plt.show()

df["label"] = (df.points >= 90).astype(int)  #false if less than 90 and true if greater than 90
df = df[["description", "points", "label"]]

df.head()

df.tail()

df = df[["description", "label"]]

train, val, test = np.split(df.sample(frac=1), [int(0.8*len(df)), int(0.9*len(df))])
# 80% of the dataset for the train, 10% for the validation, 10% for the test

len(train), len(val), len(test)

def df_to_dataset(dataframe, shuffle=True, batch_size=1024):
  df = dataframe.copy()
  labels = df.pop('label')
  df = df["description"]
  ds = tf.data.Dataset.from_tensor_slices((df, labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  ds = ds.prefetch(tf.data.AUTOTUNE)
  return ds
  #this function from tf module converts each training, validation and test set df into a tf.data.Dataset then shuffles and batches the data
  #prefetching is like trying to optimize things

train_data = df_to_dataset(train)
valid_data = df_to_dataset(val)
test_data = df_to_dataset(test)

"""# Embedding + Model

"""

#embedding is like transforming the sentences into numbers that a computer can understand
embedding = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(embedding, dtype=tf.string, trainable=True)

hub_layer(list(train_data)[0][0])
#we transformed the texts that we have in our dataset into a 50 vector containing only numbers that our model can understand

model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
#the 1st transformation will be text to numerical value

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

model.evaluate(train_data)

model.evaluate(valid_data)

history = model.fit(train_data, epochs=5, validation_data=valid_data)

model.evaluate(test_data)

"""#LSTM"""

encoder = tf.keras.layers.TextVectorization(max_tokens=2000) #max num of words we are going to remember
encoder.adapt(train_data.map(lambda text, label: text))

vocab = np.array(encoder.get_vocabulary())
vocab[:20]

model = tf.keras.Sequential([
    encoder,                                     #the encoder is what vectorizes our text
    tf.keras.layers.Embedding(  
        input_dim=len(encoder.get_vocabulary()),
        output_dim=32,                          #the size of our LSTM
        mask_zero=True                          #we use the mask to handle var sequence lengths
    ),
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

model.evaluate(train_data)
model.evaluate(valid_data)

history = model.fit(train_data, epochs=5, validation_data=valid_data)

model.evaluate(test_data)